# Generated by Django 5.1.6 on 2025-02-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0019_alter_component_id_alter_employee_id_alter_log_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$y24rlfmDipPJvPNSzRFbcJ$BJrFFqOtxCHpoRJEO4NwX7i4WDQNEWnJMPQxC2SipTk=', max_length=128),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
