# Generated by Django 5.1.6 on 2025-02-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0020_employee_password_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$870000$9bcATPxOrAbzrXYFF0PWVq$BmKGseZEzvWhlr9GmGJVPb7zkMqVzDBW73QG8rYRgf8=', max_length=128, null=True),
        ),
    ]
