# Generated by Django 5.1.6 on 2025-02-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0021_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$870000$SLiM78TIvwe3KZFjIFhSUy$hEkk0dIF1cYYCVK+5Q5kq0CQxenuszgvcgCCLRX0Jbg=', max_length=128, null=True),
        ),
    ]
